### ISSUE TITLE
Incorrect URI-template for Service-Account API client

### ISSUE THREAD

**Issue by nillga** [SchwarzIT/community-stackit-go-client#197]
Key flow authentication fails with error code 404 due to the client querying a `/service-account/v2alpha1/projects/<project-id>/service-accounts/<sa-email>/keys`-URI that is not supported. 

```
% go run create_sa_key.go
panic: call error:
HTTP status code: 404
HTTP status message: Not Found
Server response: 
URL: https://api.stackit.cloud/service-account/v2alpha1/projects/project-1/service-accounts/account-1/keys
Trace: 


goroutine 1 [running]:
main.main()
        /Users/nillg/create_sa_key.go:46 +0x23f
exit status 2
```

The proper URIs have to follow the schema `/service-account/v2/projects/<project-id>/service-accounts/<sa-email>/keys`

**Comment by do87** [comment]
fix released.
